# Generated by Django 2.2 on 2019-05-18 09:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_modifer',
            new_name='discount_modifier',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quanitiy',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.TextField(default='george'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
