# Generated by Django 2.2 on 2019-05-15 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_logmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='purchase_count',
            new_name='purchase_count',
        ),
    ]
