# Generated by Django 2.1.7 on 2019-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190515_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.TextField(default='false'),
            preserve_default=False,
        ),
    ]
