# Generated by Django 2.1.7 on 2019-04-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190416_0550'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieGenres',
            new_name='MovieGenre',
        ),
        migrations.RenameModel(
            old_name='MovieReviews',
            new_name='MovieReview',
        ),
    ]
