# Generated by Django 2.2 on 2019-05-18 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_user_is_admin'),
        ('movie', '0004_auto_20190518_0803'),
    ]

    operations = [
    ]
