# Generated by Django 2.1.7 on 2019-04-16 06:14

from django.db import migrations, models
import movie.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20190416_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=movie.custom_fields.IntegerRangeField(),
        ),
    ]
