export const GET_MOVIES = 'GET_MOVIES' 
export const GET_MOVIE = 'GET_MOVIE';
export const NO_MOVIES_FOUND = 'NO_MOVIES_FOUND'
export const GET_ORDER = 'GET_ORDER'
export const ADD_REVIEW = 'ADD_REVIEW'

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const CLEAR_SEARCH_LIST = 'CLEAR_SEARCH_LIST';
export const FAVOURITE_MOVIE = 'FAVOURITE_MOVIE';
export const UNFAVOURITE_MOVIE = 'UNFAVOURITE_MOVIE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const UPDATE_USER = 'UPDATE_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const CLEAR_UPDATE = 'CLEAR_UPDATE';
export const SEARCH_USER = 'SEARCH_USER';
export const CLEAR_SEARCH_USER = 'SEARCH_USER';
export const SET_ANONYMOUS_USER = 'SET_ANONYMOUS_USER';
export const NEW_USER_ERRORS = 'NEW_USER_ERRORS'
export const CLEAR_NEW_USER_ERRORS = 'CLEAR_NEW_USER_ERRORS'

export const GET_FEEDBACK = 'GET_FEEDBACK';
export const CLEAR_FEEDBACK = 'CLEAR_FEEDBACK';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const MOVIES_LOADING = 'MOVIES_LOADING';
export const ADD_MOVIE = 'ADD_MOVIE';
export const GET_ALL_ACCESSLOGS = 'GET_ALL_ACCESSLOGS'
export const DELETE_LOG = 'DELETE_LOG'

export const ADD_ORDER = 'ADD_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'
export const UPDATE_ORDER = 'UPDATE_ORDER'